language: python

python:
    - 2.6
    - 2.7
    - 3.4

env:
    # try all python versions with the latest stable Numpy
    - NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0 SETUP_CMD='test' YT_VERSION=3

matrix:

    include:

        # try older Numpy and yt version
        - python: 2.7
          env: NUMPY_VERSION=1.8 ASTROPY_VERSION=0.4 SETUP_CMD='test' YT_VERSION=2

before_install:

   # Add 'saucy' repositories to get latest HDF5 version
   - sudo apt-add-repository 'deb http://old-releases.ubuntu.com/ubuntu/ saucy main universe'

   # Linux packages
   - sudo apt-get update
   - sudo apt-get install build-essential g++
   - sudo apt-get install mpich2 libmpich2-dev libhdf5-7 libhdf5-dev gfortran hdf5-tools

   # Python packages
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda

   # Make sure that interactive matplotlib backends work
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start

install:
   - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
   - source activate test
   - conda install --yes numpy=$NUMPY_VERSION h5py astropy=$ASTROPY_VERSION pip matplotlib yt=$YT_VERSION;

script:
   - ./configure
   - make serial
   - sudo make install
   - python setup.py install  # to get the hyperion script installed
   - python setup.py $SETUP_CMD
