language: c

os:
  - linux
  - osx

env:
    global:
        - SETUP_XVFB=True
        - CONDA_CHANNELS='conda-forge'
        - CONDA_DEPENDENCIES='numpy astropy h5py matplotlib yt mpich hdf5'
        - SETUP_CMD='test'
        - MPLBACKEND='Agg'
    matrix:

        # Test with different versions
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.6
        - PYTHON_VERSION=3.7

        # Test with oldest supported version
        - PYTHON_VERSION=2.7
          HYPERION_HDF5_VERSION=18
          CONDA_DEPENDENCIES='numpy=1.11 astropy=2.0 h5py=2.6 matplotlib=2.0 yt=3.3 hdf5=1.8.18 mpich'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - if [[ $TRAVIS_OS_NAME == linux ]]; then conda install gcc_linux-64 gxx_linux-64 gfortran_linux-64; fi
    - if [[ $TRAVIS_OS_NAME == osx ]]; then conda install clang_osx-64 clangxx_osx-64 gfortran_osx-64; fi

script:
   - ./configure
   - make serial
   - sudo make install
   - python setup.py install  # to get the hyperion script installed
   - python setup.py $SETUP_CMD
