version: 2

jobs:
  main:
    docker:
      - image: astrofrog/hyperion-ci:1.3
    steps:
      - checkout
      - run:
          name: Compiling Fortran code
          command: |
              ./configure
              make
              make install
      - run:
          name: Installing Python package
          command: pip install .
      - run:
          name: Run full test suite (including bit-level tests)
          command: python setup.py test --enable-bit-level-tests

workflows:
  version: 2
  tests_and_docs:
    jobs:
      - main
