version: 2

jobs:
  hdf5-18:
    docker:
      - image: astrofrog/hyperion-ci-hdf5-18:1.4
    steps:
      - checkout
      - run:
          name: Initialize submodule
          command: |
              git submodule init
              git submodule update
      - run:
          name: Compiling Fortran code
          command: |
              HYPERION_HDF5_VERSION=18 ./configure
              make
              make install
      - run:
          name: Installing Numpy
          command: pip install numpy
      - run:
          name: Installing Python package
          command: pip install .[test]
      - run:
          name: Run full test suite (including bit-level tests)
          command: python setup.py test --enable-bit-level-tests
  hdf5-110:
    docker:
      - image: astrofrog/hyperion-ci-hdf5-110:1.6
    steps:
      - checkout
      - run:
          name: Initialize submodule
          command: |
              git submodule init
              git submodule update
      - run:
          name: Compiling Fortran code
          command: |
              ./configure
              make
              make install
      - run:
          name: Installing Numpy
          command: pip3 install numpy
      - run:
          name: Installing Python package
          command: pip3 install .[test]
      - run:
          name: Run full test suite (including bit-level tests)
          command: python3 setup.py test --enable-bit-level-tests

workflows:
  version: 2
  tests_and_docs:
    jobs:
      - hdf5-18
      - hdf5-110
